import { buildOutlineSchema, useSavedControls } from "@/engine/leva/savedControls";

/**
 * 「비밀 복도」 — 왼쪽 벽 뒤 복도와 그 안의 벽함·자판기 자리·옆문·끝문·복도등.
 * 복도는 건물 밖으로 이어지는 통로라 방보다 길다. 양 끝이 어둠으로 사라져야 「계속 이어진다」로 읽힌다.
 * 깊이 감광은 곡선 대신 바닥값(minBrightness)과 벽 배수만 올린다 — 곡선을 만지면 복도가 짧아 보인다.
 * 주름선 회색(#808080)은 복도 것만의 색이다. 수사본부실은 자기 색을 따로 쓴다.
 */
export function useCorridorControls() {
  return useSavedControls("비밀 복도", {
    visible: { value: true, label: "보이기" },
    openness: { value: 1, min: 0, max: 1, step: 0.01, label: "열림" },
    showBlocker: { value: false, label: "막이보이기" },
    outerX: { value: -31, min: -45, max: -21, step: 0.5, label: "바깥x" },
    startZ: { value: -60, min: -60, max: 12, step: 0.5, label: "z시작" },
    endZ: { value: 25.5, min: -14, max: 60, step: 0.5, label: "z끝" },
    height: { value: 8, min: 4, max: 12, step: 0.2, label: "높이" },
    doorZ: { value: 4, min: -14, max: 12, step: 0.2, label: "문z" },
    doorWidth: { value: 3.6, min: 2, max: 8, step: 0.1, label: "문폭" },
    doorHeight: { value: 5.7, min: 3, max: 11, step: 0.1, label: "문높이" },
    doorThickness: { value: 0.2, min: 0.2, max: 2, step: 0.05, label: "문두께" },
    wallColor: { value: "#525b69", label: "벽색" },
    baseboardColor: { value: "#4e5462", label: "아랫단색" },
    floorColor: { value: "#2d2f31", label: "바닥색" },
    ceilingColor: { value: "#23262b", label: "천장색" },
    edgeRubble: { value: false, label: "테두리잔해" },
    rubbleCount: { value: 0, min: 0, max: 40, step: 1, label: "잔해" },
    rubbleColor: { value: "#3b4048", label: "잔해색" },
    roughness: { value: 0.32, min: 0, max: 0.6, step: 0.01, label: "거칠기" },
    depthDarkness: { value: 0.6, min: 0, max: 1, step: 0.01, label: "깊이어둠" },
    falloff: { value: 33, min: 5, max: 80, step: 1, label: "감쇠거리" },
    minBrightness: { value: 0.66, min: 0, max: 1, step: 0.01, label: "최소밝기" },
    wallBrightness: { value: 1.5, min: 0.5, max: 2.5, step: 0.05, label: "벽밝기" },
    endDarkness: { value: 0.58, min: 0, max: 0.9, step: 0.01, label: "끝쪽어둠" },
    endCurve: { value: 1.8, min: 0.5, max: 4, step: 0.1, label: "끝쪽기울기" },
    pipesVisible: { value: true, label: "배관보이기" },
    pipeXRatio: { value: 0.62, min: 0, max: 1, step: 0.02, label: "배관x비율" },
    pipeSag: { value: 0.1, min: 0.02, max: 2, step: 0.02, label: "배관처짐" },
    pipeLargeRadius: { value: 0.18, min: 0.05, max: 0.6, step: 0.01, label: "배관큰지름" },
    pipeSmallRadius: { value: 0.1, min: 0.03, max: 0.3, step: 0.01, label: "배관작은지름" },
    pipeTrayWidth: { value: 1.0, min: 0.3, max: 2, step: 0.05, label: "배관트레이폭" },
    pipeRungSpacing: { value: 1.7, min: 0.5, max: 6, step: 0.1, label: "배관가로대간격" },
    pipeHangerSpacing: { value: 6, min: 2, max: 20, step: 0.5, label: "배관행어간격" },
    pipeColor: { value: "#474c53", label: "배관색" },
    pipeTrayColor: { value: "#474c54", label: "배관트레이색" },
    pipeHangerColor: { value: "#3e434a", label: "배관행어색" },
    pipeBrightness: { value: 0.7, min: 0.3, max: 2.5, step: 0.05, label: "배관밝기" },
    cabinetGrime: { value: 1, min: 0, max: 2, step: 0.05, label: "함때" },
    cabinetFittingColor: { value: "#7b828a", label: "함부속색" },
    panelVisible: { value: true, label: "배전반보이기" },
    panelZRatio: { value: 0.88, min: 0, max: 1, step: 0.01, label: "배전반z비율" },
    panelWidth: { value: 1.6, min: 0.6, max: 3, step: 0.05, label: "배전반폭" },
    panelHeight: { value: 2.0, min: 0.8, max: 4, step: 0.05, label: "배전반높이" },
    panelDepth: { value: 0.4, min: 0.1, max: 1, step: 0.02, label: "배전반깊이" },
    panelBaseHeight: { value: 2.375, min: 0.5, max: 6, step: 0.025, label: "배전반바닥높이" },
    panelColor: { value: "#4d5055", label: "배전반색" },
    panelDoorColor: { value: "#5e646c", label: "배전반문색" },
    panelLabelColor: { value: "#c9a83c", label: "배전반라벨색" },
    panelNumber: { value: "N-3", label: "배전반번호" },
    panelConduit: { value: true, label: "배전반전선관" },
    panelDoorOpenAngle: { value: 102, min: 30, max: 130, step: 1, label: "배전반문열림각" },
    hydrantVisible: { value: true, label: "소화전보이기" },
    hydrantZRatio: { value: 0.88, min: 0, max: 1, step: 0.01, label: "소화전z비율" },
    hydrantWidth: { value: 1.4, min: 0.6, max: 3, step: 0.05, label: "소화전폭" },
    hydrantHeight: { value: 2.25, min: 0.8, max: 4, step: 0.05, label: "소화전높이" },
    hydrantDepth: { value: 0.38, min: 0.1, max: 1, step: 0.02, label: "소화전깊이" },
    hydrantBaseHeight: { value: 2.25, min: 0.5, max: 6, step: 0.05, label: "소화전바닥높이" },
    hydrantColor: { value: "#804239", label: "소화전색" },
    hydrantDoorColor: { value: "#79352c", label: "소화전문색" },
    hydrantLabelColor: { value: "#cb4e43", label: "소화전라벨색" },
    hydrantDoorOpenAngle: { value: 102, min: 30, max: 130, step: 1, label: "소화전문열림각" },
    clutterVisible: { value: true, label: "잡동사니보이기" },
    clutterDensity: { value: 0.08, min: 0, max: 2, step: 0.05, label: "잡동사니밀도" },
    clutterSize: { value: 1.45, min: 0.6, max: 3, step: 0.05, label: "잡동사니크기" },
    puddleCount: { value: 1, min: 0, max: 12, step: 1, label: "웅덩이수" },
    corrosionVisible: { value: true, label: "부식보이기" },
    corrosionFloorCount: { value: 12, min: 0, max: 60, step: 1, label: "부식바닥수" },
    corrosionWallCount: { value: 18, min: 0, max: 80, step: 1, label: "부식벽수" },
    crackCount: { value: 8, min: 0, max: 40, step: 1, label: "벽금수" },
    corrosionSize: { value: 1.3, min: 0.3, max: 3, step: 0.05, label: "부식크기" },
    vendingVisible: { value: true, label: "자판기보이기" },
    vendingDepth: { value: 2.4, min: 1.2, max: 3.5, step: 0.05, label: "자판기깊이" },
    coffeeChoice: { value: "없음", options: ["없음", "핫", "아이스"], label: "커피선택" },
    forcedCan: { value: -1, min: -1, max: 5, step: 1, label: "음료뽑힌캔강제" },
    forcedCup: { value: false, label: "커피컵" },
    forcedCoffeeDoorOpen: { value: 0, min: 0, max: 1, step: 0.05, label: "커피문열림" },
    sideDoorsVisible: { value: true, label: "측면문보이기" },
    sideDoorCount: { value: 3, min: 0, max: 6, step: 1, label: "측면문개수" },
    sideDoorWidth: { value: 3.0, min: 2, max: 5, step: 0.1, label: "측면문폭" },
    sideDoorHeight: { value: 6.4, min: 4, max: 9, step: 0.1, label: "측면문높이" },
    sideDoorThickness: { value: 0.09, min: 0.04, max: 0.2, step: 0.01, label: "측면문두께" },
    sideDoorFrameProtrusion: { value: 0.06, min: 0, max: 0.25, step: 0.01, label: "측면문틀돌출" },
    sideDoorInset: { value: 0.03, min: 0, max: 0.1, step: 0.01, label: "측면문내림" },
    sideDoorThresholdProtrusion: { value: 0.06, min: 0, max: 0.4, step: 0.01, label: "측면문발판돌출" },
    sideDoorStart: { value: 0.18, min: 0, max: 1, step: 0.01, label: "측면문시작" },
    sideDoorEnd: { value: 0.78, min: 0, max: 1, step: 0.01, label: "측면문끝" },
    sideDoorColor: { value: "#5a5f62", label: "측면문색" },
    sideDoorRevealColor: { value: "#313339", label: "측면문리빌색" },
    sideDoorGapColor: { value: "#303136", label: "측면문틈색" },
    sideDoorPanelLineColor: { value: "#3f4346", label: "측면문패널선색" },
    sideDoorHingeColor: { value: "#2a2c33", label: "측면문경첩색" },
    sideDoorKnobColor: { value: "#2e2e2f", label: "측면문손잡이색" },
    sideDoorLockPlateColor: { value: "#5a5148", label: "측면문잠금판색" },
    sideDoorKeyholeColor: { value: "#0c0e11", label: "측면문열쇠구멍색" },
    sideDoorThresholdColor: { value: "#2b2d2f", label: "측면문턱색" },
    sideDoorBoardColor: { value: "#36210d", label: "측면문판자색" },
    sideDoorNailColor: { value: "#363534", label: "측면문못색" },
    sideDoorOutline: { value: true, label: "측면문외곽선" },
    sideDoorOutlineColor: { value: "#131314", label: "측면문외곽선색" },
    sideDoorOutlineWidth: { value: 5, min: 0, max: 20, step: 0.5, label: "측면문외곽선굵기" },
    sideDoorBrightness: { value: 1.85, min: 0.3, max: 3, step: 0.05, label: "측면문밝기" },
    sideDoorGrime: { value: 0.6, min: 0, max: 2, step: 0.05, label: "측면문때" },
    sideDoorBoards: { value: true, label: "측면문판자" },
    endDoorVisible: { value: true, label: "끝문보이기" },
    endDoorWidth: { value: 2.4, min: 2, max: 6, step: 0.1, label: "끝문폭" },
    endDoorHeight: { value: 6.1, min: 4, max: 9, step: 0.1, label: "끝문높이" },
    endDoorColor: { value: "#1c1d21", label: "끝문색" },
    endDoorFrameColor: { value: "#1e2024", label: "끝문틀색" },
    endDoorHandleColor: { value: "#cdd9e5", label: "끝문손잡이색" },
    endDoorLineColor: { value: "#41484b", label: "끝문라인색" },
    endDoorContrast: { value: 1.35, min: 1, max: 3, step: 0.05, label: "끝문대비" },
    endDoorCasingWidth: { value: 0.75, min: 0.2, max: 2, step: 0.05, label: "끝문선폭" },
    endDoorCasingDepth: { value: 0.15, min: 0.05, max: 0.6, step: 0.01, label: "끝문선두께" },
    endDoorThickness: { value: 0.05, min: 0.05, max: 0.5, step: 0.01, label: "끝문두께" },
    endDoorBrightness: { value: 0.95, min: 0.2, max: 2.5, step: 0.05, label: "끝문밝기보정" },
    exitSign: { value: true, label: "유도등" },
    exitSignScale: { value: 0.62, min: 0.2, max: 1.4, step: 0.02, label: "유도등크기" },
    exitSignHeight: { value: 0.65, min: 0, max: 3, step: 0.05, label: "유도등높이" },
    exitSignRimColor: { value: "#31333b", label: "유도등테색" },
    exitSignColor: { value: "#3f9e63", label: "유도등바탕색" },
    freeRoam: { value: false, label: "자유이동" },
    lightsOn: { value: true, label: "불켜기" },
    lightCount: { value: 6, min: 1, max: 10, step: 1, label: "등개수" },
    lightWidth: { value: 1.1, min: 0.4, max: 3, step: 0.05, label: "등폭" },
    lightLength: { value: 4, min: 1, max: 10, step: 0.1, label: "등길이" },
    lightRotation: { value: 0, min: -Math.PI, max: Math.PI, step: 0.01, label: "등회전" },
    lightDrop: { value: 0.12, min: 0, max: 2, step: 0.01, label: "등내림" },
    lightFrameColor: { value: "#38383b", label: "등틀색" },
    lightPanelColor: { value: "#fffce7", label: "등판색" },
    lightGrime: { value: 0.8, min: 0, max: 2, step: 0.05, label: "등때" },
    lightGlow: { value: 1.1, min: 0.3, max: 4, step: 0.05, label: "등발광" },
    lightAngle: { value: 0.51, min: 0.2, max: 1.5, step: 0.01, label: "빛각도" },
    lightPenumbra: { value: 0.18, min: 0, max: 1, step: 0.01, label: "빛퍼짐" },
    lightDistance: { value: 16, min: 5, max: 80, step: 1, label: "빛거리" },
    flicker: { value: true, label: "깜빡임" },
    lightIntensity: { value: 14.5, min: 0, max: 60, step: 0.5, label: "불세기" },
    lightColor: { value: "#8fa6c4", label: "불색" },
    ...buildOutlineSchema({ width: 5, color: "#131314", crease: true, creaseAngle: 40, creaseColor: "#808080" }),
  });
}

export type CorridorValues = ReturnType<typeof useCorridorControls>;
