import { useSavedControls } from "@/engine/leva/savedControls";
import type { WorkLampPuzzleValues } from "@/props/workLampPuzzle/controls";

/**
 * 「작업등 퍼즐」 — 비밀 복도 반대쪽 끝의 퍼즐. 열쇠가 WorkLampPuzzleValues 필드와 같아 통째로 넘긴다.
 * 늘 보여야 한다(visible 기본 true — 저장된 false 는 강제 기본값이 지운다).
 * darkBoundaryZ 40 은 복도 끝벽(25.5)을 넉넉히 넘겨, 시작하자마자 자판기 쪽까지 통째로 어둡게 한다.
 */
export function useWorkLampPuzzleControls(): WorkLampPuzzleValues {
  return useSavedControls("작업등 퍼즐", {
    visible: { value: true, label: "보이기" },
    floorX: { value: -25.2, min: -31, max: -20, step: 0.1, label: "바닥x" },
    floorY: { value: 0.42, min: 0, max: 3, step: 0.02, label: "바닥y" },
    floorZ: { value: -54, min: -60, max: -20, step: 0.5, label: "바닥z" },
    floorTilt: { value: 0.35, min: -Math.PI, max: Math.PI, step: 0.05, label: "바닥기울기" },
    junctionAZ: { value: -53.3, min: -60, max: -20, step: 0.5, label: "A_z" },
    junctionBZ: { value: -49.5, min: -60, max: -20, step: 0.5, label: "B_z" },
    junctionCZ: { value: -39, min: -60, max: -20, step: 0.5, label: "C_z" },
    boxY: { value: 4.0, min: 1, max: 7, step: 0.05, label: "함y" },
    boxWidth: { value: 0.5, min: 0.2, max: 1.2, step: 0.02, label: "함폭" },
    boxHeight: { value: 0.66, min: 0.3, max: 1.5, step: 0.02, label: "함높이" },
    boxDepth: { value: 0.24, min: 0.1, max: 0.6, step: 0.01, label: "함깊이" },
    boxWear: { value: 1, min: 0, max: 2, step: 0.05, label: "함때" },
    boxBrightness: { value: 1.5, min: 0.3, max: 3, step: 0.05, label: "함밝기" },
    markAOrder: { value: 2, min: 1, max: 3, step: 1, label: "A_칸" },
    markAGlyph: { value: "R", label: "A_글자" },
    markBOrder: { value: 3, min: 1, max: 3, step: 1, label: "B_칸" },
    markBGlyph: { value: "N", label: "B_글자" },
    markCOrder: { value: 1, min: 1, max: 3, step: 1, label: "C_칸" },
    markCGlyph: { value: "K", label: "C_글자" },
    markAZ: { value: -52.5, min: -60, max: -20, step: 0.2, label: "A_자국z" },
    markBZ: { value: -44.6, min: -60, max: -20, step: 0.2, label: "B_자국z" },
    markCZ: { value: -38.2, min: -60, max: -20, step: 0.2, label: "C_자국z" },
    markY: { value: 3.4, min: 0.5, max: 7, step: 0.05, label: "자국y" },
    markSize: { value: 1.1, min: 0.3, max: 3, step: 0.05, label: "자국크기" },
    markColor: { value: "#dfe6ea", label: "자국색" },
    markSeed: { value: 3, min: 0, max: 40, step: 1, label: "자국씨" },
    markOffset: { value: 0.05, min: 0.01, max: 0.4, step: 0.01, label: "자국띄움" },
    markBOffset: { value: 0.28, min: 0.01, max: 0.8, step: 0.01, label: "B_자국띄움" },
    lampScale: { value: 1, min: 0.3, max: 2.5, step: 0.05, label: "램프크기" },
    metalColor: { value: "#8d949c", label: "쇠색" },
    rubberColor: { value: "#2b2e33", label: "고무색" },
    bulbColor: { value: "#fff6d8", label: "전구색" },
    floorGlint: { value: 0.5, min: 0, max: 2, step: 0.05, label: "바닥반짝" },
    lightColor: { value: "#ffe9b8", label: "불색" },
    handIntensity: { value: 8, min: 0, max: 30, step: 0.1, label: "손세기" },
    handDistance: { value: 13, min: 1, max: 40, step: 0.5, label: "손거리" },
    handLightForward: { value: 0.9, min: -1, max: 3, step: 0.05, label: "손빛앞" },
    handLightDown: { value: 1.1, min: -1, max: 3, step: 0.05, label: "손빛아래" },
    pluggedIntensity: { value: 34, min: 0, max: 80, step: 0.5, label: "꽂힘세기" },
    pluggedDistance: { value: 22, min: 1, max: 60, step: 0.5, label: "꽂힘거리" },
    handForward: { value: 1.25, min: 0.3, max: 3, step: 0.05, label: "손앞" },
    handDown: { value: 0.62, min: -1, max: 2, step: 0.02, label: "손아래" },
    handSide: { value: 0.46, min: -1.5, max: 1.5, step: 0.02, label: "손옆" },
    handScale: { value: 0.72, min: 0.2, max: 2, step: 0.02, label: "손크기" },
    handTilt: { value: 0.22, min: -1.6, max: 1.6, step: 0.02, label: "손기울기" },
    handTwist: { value: -0.18, min: -1.6, max: 1.6, step: 0.02, label: "손비틀기" },
    handGlow: { value: 0.5, min: 0, max: 2, step: 0.05, label: "손켜짐" },
    floorIntensity: { value: 3.4, min: 0, max: 30, step: 0.1, label: "바닥세기" },
    floorDistance: { value: 7, min: 1, max: 40, step: 0.5, label: "바닥거리" },
    floorGlow: { value: 0.45, min: 0, max: 2, step: 0.05, label: "바닥켜짐" },
    dropDistance: { value: 3.6, min: 0.5, max: 6, step: 0.1, label: "놓는거리" },
    breakerVisible: { value: true, label: "차단기보이기" },
    breakerZ: { value: -55.5, min: -60, max: -20, step: 0.2, label: "차단기z" },
    breakerY: { value: 3.9, min: 1, max: 7, step: 0.05, label: "차단기y" },
    breakerWidth: { value: 1.5, min: 0.4, max: 2.5, step: 0.05, label: "차단기폭" },
    breakerHeight: { value: 2.0, min: 0.5, max: 3, step: 0.05, label: "차단기높이" },
    breakerDepth: { value: 0.45, min: 0.1, max: 0.8, step: 0.02, label: "차단기깊이" },
    lockScale: { value: 1.9, min: 0.4, max: 3, step: 0.05, label: "자물쇠크기" },
    lockOperateDistance: { value: 0.8, min: 0.3, max: 2, step: 0.05, label: "자물쇠조작거리" },
    lockDepth: { value: 0.05, min: -0.2, max: 0.5, step: 0.005, label: "자물쇠깊이" },
    lockHeight: { value: -0.2, min: -0.8, max: 0.8, step: 0.005, label: "자물쇠높이" },
    lockSide: { value: -0.19, min: -0.4, max: 0.4, step: 0.005, label: "자물쇠옆" },
    lockAnswer: { value: "KRN", label: "정답" },
    lockSeed1: { value: 0, min: 0, max: 9, step: 1, label: "씨1" },
    lockSeed2: { value: 0, min: 0, max: 9, step: 1, label: "씨2" },
    lockSeed3: { value: 0, min: 0, max: 9, step: 1, label: "씨3" },
    lightCount: { value: 3, min: 0, max: 8, step: 1, label: "켜질등수" },
    lightStartZ: { value: -54, min: -60, max: -10, step: 0.5, label: "등z시작" },
    lightEndZ: { value: -36, min: -60, max: -10, step: 0.5, label: "등z끝" },
    darkBoundaryZ: { value: 40, min: -60, max: 60, step: 0.5, label: "어둠경계z" },
    startDark: { value: true, label: "처음어둡게" },
    darkFactor: { value: 0.05, min: 0, max: 1, step: 0.01, label: "어둠계수" },
    halfPowerBoundaryZ: { value: -30, min: -60, max: 26, step: 0.5, label: "반경계z" },
    binGeneralZ: { value: -41.9, min: -60, max: -20, step: 0.1, label: "통z일반" },
    binPlasticZ: { value: -40.1, min: -60, max: -20, step: 0.1, label: "통z플라" },
    binOffset: { value: 0.05, min: 0, max: 2, step: 0.01, label: "통띄움" },
    trashScale: { value: 1.25, min: 0.5, max: 3, step: 0.05, label: "쓰레기크기" },
    paintingZ: { value: -41.2, min: -60, max: -20, step: 0.1, label: "그림z" },
    paintingY: { value: 5.15, min: 1, max: 7, step: 0.05, label: "그림y" },
    paintingWidth: { value: 2.6, min: 1, max: 5, step: 0.05, label: "그림폭" },
    switchPanelY: { value: 4.35, min: 1, max: 7, step: 0.05, label: "시험반y" },
    switchPanelSide: { value: -2.55, min: -5, max: 5, step: 0.05, label: "시험반옆" },
  });
}
