"""create anonymous sessions

Revision ID:41648d0b186d
Revises:
Create Date:2026-09-14 10:10:01.661326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '41648d0b186d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_sessions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_anonymous_sessions_expires_at', 'anonymous_sessions', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_anonymous_sessions_expires_at', table_name='anonymous_sessions')
    op.drop_table('anonymous_sessions')
    # ### end Alembic commands ###
