"""create play sessions

Revision ID: 525df42531f7
Revises: 41648d0b186d
Create Date: 2026-09-14 17:21:32.240410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '525df42531f7'
down_revision: Union[str, Sequence[str], None] = '41648d0b186d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('play_sessions',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('anonymous_session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('case_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('state_json', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('completed_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.ForeignKeyConstraint(['anonymous_session_id'], ['anonymous_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_play_sessions_anonymous_session_id', 'play_sessions', ['anonymous_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_play_sessions_anonymous_session_id', table_name='play_sessions')
    op.drop_table('play_sessions')
    # ### end Alembic commands ###
