"""create interaction events

Revision ID: 63c92fd744f9
Revises: 525df42531f7
Create Date: 2026-09-18 11:26:32.002554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63c92fd744f9'
down_revision: Union[str, Sequence[str], None] = '525df42531f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction_events',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('play_session_id', sa.CHAR(length=36), nullable=False),
    sa.Column('client_event_id', sa.CHAR(length=36), nullable=False),
    sa.Column('interaction_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('payload_json', mysql.JSON(), nullable=False),
    sa.Column('result_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('response_json', mysql.JSON(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['play_session_id'], ['play_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('play_session_id', 'client_event_id', name='uq_interaction_events_play_session_client_event')
    )
    op.create_index('ix_interaction_events_play_session_id', 'interaction_events', ['play_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_interaction_events_play_session_id', table_name='interaction_events')
    op.drop_table('interaction_events')
    # ### end Alembic commands ###
