"""add interaction client timestamp

Revision ID: d7481874fb1c
Revises: 63c92fd744f9
Create Date: 2026-09-29 10:36:51.015856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd7481874fb1c'
down_revision: Union[str, Sequence[str], None] = '63c92fd744f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interaction_events', sa.Column('client_timestamp', mysql.DATETIME(fsp=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interaction_events', 'client_timestamp')
    # ### end Alembic commands ###
