export const 사이드킥모션목록 = [
  ["자동", "자동 · 게임 상태"],
  ["A_TPose", "A/T 기본 포즈"],
  ["Idle_Loop", "대기"],
  ["Idle_Talking_Loop", "말하며 대기"],
  ["Idle_Torch_Loop", "횃불 대기"],
  ["Walk_Loop", "걷기"],
  ["Walk_Formal_Loop", "정중한 걷기"],
  ["Jog_Fwd_Loop", "조깅"],
  ["Sprint_Loop", "전력 질주"],
  ["Crouch_Idle_Loop", "앉은 대기"],
  ["Crouch_Fwd_Loop", "앉아 걷기"],
  ["Jump_Start", "점프 시작"],
  ["Jump_Loop", "점프 공중"],
  ["Jump_Land", "점프 착지"],
  ["Roll", "구르기"],
  ["Dance_Loop", "춤"],
  ["Interact", "상호작용"],
  ["PickUp_Table", "테이블 물건 줍기"],
  ["Push_Loop", "밀기"],
  ["Fixing_Kneeling", "무릎 꿇고 수리"],
  ["Sitting_Enter", "앉기 시작"],
  ["Sitting_Idle_Loop", "앉은 대기"],
  ["Sitting_Talking_Loop", "앉아서 말하기"],
  ["Sitting_Exit", "일어나기"],
  ["Swim_Idle_Loop", "제자리 수영"],
  ["Swim_Fwd_Loop", "전진 수영"],
  ["Hit_Chest", "가슴 피격"],
  ["Hit_Head", "머리 피격"],
  ["Death01", "사망"],
  ["Punch_Jab", "잽"],
  ["Punch_Cross", "크로스 펀치"],
  ["Spell_Simple_Enter", "마법 자세 시작"],
  ["Spell_Simple_Idle_Loop", "마법 대기"],
  ["Spell_Simple_Shoot", "마법 발사"],
  ["Spell_Simple_Exit", "마법 자세 해제"],
  ["Sword_Idle", "검 대기"],
  ["Sword_Attack", "검 공격"],
  ["Pistol_Idle_Loop", "권총 대기"],
  ["Pistol_Aim_Up", "권총 위 조준"],
  ["Pistol_Aim_Neutral", "권총 정면 조준"],
  ["Pistol_Aim_Down", "권총 아래 조준"],
  ["Pistol_Shoot", "권총 사격"],
  ["Pistol_Reload", "권총 재장전"],
  ["Driving_Loop", "운전"],
];

export const 기본사이드킥설정 = {
  motion: "자동",
  head: 1,
  hair: 4,
  brows: 1,
  ears: 1,
  facialHair: 0,
  nose: 1,
  teeth: 1,
  top: 2,
  bottom: 2,
  shoes: 2,
  headwear: 0,
  faceAccessory: 0,
  backAccessory: 0,
  hipFront: 0,
  hipBack: 0,
  hipSide: 0,
  shoulderAccessory: 0,
  elbowAccessory: 0,
  kneeAccessory: 0,
  feminine: 1,
  heavy: 0,
  buff: 0,
  skinny: 0.15,
  skinColor: "#f0b789",
  hairColor: "#69a9c7",
  topColor: "#d7e8ef",
  bottomColor: "#333840",
  shoesColor: "#424850",
  accessoryColor: "#8aa7b7",
};

export const 외형선택지 = {
  head: [[1, "둥근 얼굴"], [2, "각진 얼굴"]],
  hair: Array.from({ length: 11 }, (_, i) => [i + 1, `헤어 ${i + 1}`]),
  brows: Array.from({ length: 10 }, (_, i) => [i + 1, `눈썹 ${i + 1}`]),
  ears: Array.from({ length: 10 }, (_, i) => [i + 1, `귀 ${i + 1}`]),
  facialHair: [[0, "없음"], ...Array.from({ length: 10 }, (_, i) => [i + 1, `수염 ${i + 1}`])],
  nose: Array.from({ length: 11 }, (_, i) => [i + 1, `코 ${i + 1}`]),
  teeth: Array.from({ length: 10 }, (_, i) => [i + 1, `치아 ${i + 1}`]),
  top: [[1, "기본 신체"], [2, "SF 상의"], [3, "기사 상의"]],
  bottom: [[1, "기본 하의"], [2, "SF 하의"], [3, "기사 하의"]],
  shoes: [[1, "맨발"], [2, "SF 신발"], [3, "기사 신발"]],
  headwear: [[0, "없음"], [1, "SF 헬멧"], [2, "SF 헬멧 2"], [3, "기사 투구"], [4, "악당 투구"]],
  faceAccessory: [[0, "없음"], [1, "SF 얼굴 장비"], [2, "기사 얼굴 장비"]],
  backAccessory: [[0, "없음"], [1, "SF 등 장비"], [2, "기사 등 장비"]],
  hipFront: [[0, "없음"], [1, "SF 허리 앞"], [2, "기사 허리 앞"]],
  hipBack: [[0, "없음"], [1, "SF 허리 뒤"], [2, "SF 허리 뒤 2"], [3, "기사 허리 뒤"]],
  hipSide: [[0, "없음"], [1, "SF 허리 옆"], [2, "SF 허리 옆 2"], [3, "기사 허리 옆"]],
  shoulderAccessory: [[0, "없음"], [1, "SF 어깨 장비"], [2, "SF 어깨 장비 2"], [3, "기사 어깨 장비"]],
  elbowAccessory: [[0, "없음"], [1, "SF 팔꿈치 장비"], [2, "기사 팔꿈치 장비"]],
  kneeAccessory: [[0, "없음"], [1, "SF 무릎 장비"], [2, "기사 무릎 장비"]],
};

export const 외형항목이름 = {
  head: "얼굴",
  hair: "헤어",
  brows: "눈썹",
  ears: "귀",
  facialHair: "수염",
  nose: "코",
  teeth: "치아",
  top: "상의",
  bottom: "하의",
  shoes: "신발",
  headwear: "머리 장비",
  faceAccessory: "얼굴 장비",
  backAccessory: "등 장비",
  hipFront: "허리 앞",
  hipBack: "허리 뒤",
  hipSide: "허리 옆",
  shoulderAccessory: "어깨 장비",
  elbowAccessory: "팔꿈치 장비",
  kneeAccessory: "무릎 장비",
};
